// lib/models/nickname_model.dart
// 100 romantic nicknames for My Wifeu My Grace

class NicknameData {
  NicknameData._();

  /// The prefix shown before each name
  static const String prefix = 'I Love You More Than You,';

  /// 100 unique romantic nicknames
  static const List<String> names = [
    'My Wifeu 💍',
    'My Grace ✨',
    'My Heartbeat 💓',
    'My Dil Ka Tukda 💕',
    'My Queen 👑',
    'My Princess 🌸',
    'My Angel 😇',
    'My Moon 🌙',
    'My Everything 🌟',
    'My Home 🏡',
    'Love of My Life ❤️',
    'Forever Mine 💫',
    'My Soulmate 🔮',
    'My Baby 🍼',
    'My Cutie 🌺',
    'My Sweetheart 🍬',
    'My Sunshine ☀️',
    'My Rose 🌹',
    'My Pari 🧚',
    'My Jaan 💗',
    'My Life ✨',
    'My Dil 💛',
    'My Wonder Woman 🦸‍♀️',
    'My Universe 🌌',
    'My Star ⭐',
    'My Daydream 🌤️',
    'My Poem 📜',
    'My Song 🎵',
    'My Prayer 🤲',
    'My Miracle 🌠',
    'My Treasure 💎',
    'My Blessing 🙏',
    'My World 🌍',
    'My Safe Place 🛡️',
    'My Peace ☮️',
    'My Calm 🌊',
    'My Warmth 🔥',
    'My Light 💡',
    'My Reason 🌿',
    'My Purpose 🎯',
    'My Destiny 🌠',
    'My Chosen One 💫',
    'My Forever 🕊️',
    'My Always ♾️',
    'My Infinity ∞',
    'My Whole Heart 💖',
    'My Pretty Girl 🌸',
    'My Lovely 💐',
    'My Darling 🌺',
    'My Honey 🍯',
    'My Sugar 🍬',
    'My Candyfloss 🩷',
    'My Cupcake 🧁',
    'My Buttercup 🌻',
    'My Peach 🍑',
    'My Petal 🌷',
    'My Bloom 🌼',
    'My Garden 🌿',
    'My Melody 🎶',
    'My Lullaby 🎵',
    'My Symphony 🎻',
    'My Muse 🎨',
    'My Dream Come True 💭',
    'My Best Dream 🌙',
    'My Answered Prayer 🙏',
    'My Gentle Soul 🕊️',
    'My Kind Heart 💝',
    'My Soft Place 🌸',
    'My Tender Love 💓',
    'My Precious 💎',
    'My Gem 💍',
    'My Diamond 💠',
    'My Crown 👑',
    'My Glory 🌟',
    'My Grace-ful One ✨',
    'My Beautiful Disaster 🌪️❤️',
    'My Perfect Imperfection 💫',
    'My Chaos and Peace 🌊',
    'My Storm and Shelter ⛅',
    'My Rain and Rainbow 🌈',
    'My Night and Morning 🌙☀️',
    'My Laugh Track 😄',
    'My Happy Place 🎠',
    'My Joy 🎉',
    'My Giggle 😂',
    'My Blush 🌹',
    'My Shy One 🙈',
    'My Proud One 🦁',
    'My Brave Heart 💪❤️',
    'My Soft Fire 🕯️',
    'My Quiet Strength 🌿',
    'My Constant 🌟',
    'My Anchor ⚓',
    'My Foundation 🏛️',
    'My Tomorrow ⬆️',
    'My Today 📅',
    'My Every Yesterday 🕰️',
    'My Timeless Love ⏳',
    'My Grace-ful Wifeu 💍✨',
  ];
}
